
# =========================================================================
# INPUT PLUGINS (collect basic system metrics)
# =========================================================================


[[inputs.internal]]

#################################################### SMO S40 ####################################################
[[inputs.modbus]]
	name = "SMO S40"
	timeout = "1s"
	busy_retries = 2
	busy_retries_wait = "100ms"
	controller = "tcp://192.168.50.55:502"
	configuration_type= "request"
	tagexclude = ["slave_id", "type", "name", "host"]


[[inputs.modbus.request]]
	slave_id=1
	byte_order = "CDAB"
	register = "input"
	fields = [
		{ address = 1,		name = "Aktuelle Außentemperatur (BT1)",   							type = "INT16",   	scale = 0.1		},
		{ address = 1028, 	name = "Prio", 														type = "INT16", 	scale = 1.0		},
]

[inputs.modbus.request.tags]
	origin = "smos40"	# IMPORTv2: change to lowercase!
	bucket = "knv"		# IMPORTv2: change to lowercase!
