#################################################### shelly_pro3em ####################################################

[[inputs.modbus]]
  name = "shelly_pro3em"
  timeout = "1s"
  busy_retries = 2
  busy_retries_wait = "100ms"
  controller = "tcp://192.168.50.20:502"
  configuration_type = "request"
  tagexclude = ["slave_id", "type", "name", "host"]
  optimization = "none"

[[inputs.modbus.request]]
  slave_id = 1
  byte_order = "CDAB"
  register = "input"
  fields = [
    # TOTAL
    { address = 1011, name = "total_current_a", type = "FLOAT32" },
    { address = 1013, name = "total_active_power_w", type = "FLOAT32" },
    { address = 1015, name = "total_apparent_power_va", type = "FLOAT32" },

    # PHASE A
    { address = 1020, name = "phase_a_voltage_v", type = "FLOAT32" },
    { address = 1022, name = "phase_a_current_a", type = "FLOAT32" },
    { address = 1024, name = "phase_a_active_power_w", type = "FLOAT32" },
    { address = 1026, name = "phase_a_apparent_power_va", type = "FLOAT32" },
    { address = 1028, name = "phase_a_power_factor", type = "FLOAT32" },

    # PHASE B
    { address = 1040, name = "phase_b_voltage_v", type = "FLOAT32" },
    { address = 1042, name = "phase_b_current_a", type = "FLOAT32" },
    { address = 1044, name = "phase_b_active_power_w", type = "FLOAT32" },
    { address = 1046, name = "phase_b_apparent_power_va", type = "FLOAT32" },
    { address = 1048, name = "phase_b_power_factor", type = "FLOAT32" },

    # PHASE C
    { address = 1060, name = "phase_c_voltage_v", type = "FLOAT32" },
    { address = 1062, name = "phase_c_current_a", type = "FLOAT32" },
    { address = 1064, name = "phase_c_active_power_w", type = "FLOAT32" },
    { address = 1066, name = "phase_c_apparent_power_va", type = "FLOAT32" },
    { address = 1068, name = "phase_c_power_factor", type = "FLOAT32" },
  ]

[inputs.modbus.request.tags]
  origin = "shelly_pro3em"
