[[processors.override]]
  namepass = ["modbus"]

  name_override = "wp"

  [processors.override.tagpass]
    Origin = ["wp"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "smos40"

  [processors.override.tagpass]
    Origin = ["smos40"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "klimasystem2"

  [processors.override.tagpass]
    Origin = ["klimasystem2"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "klimasystem3"

  [processors.override.tagpass]
    Origin = ["klimasystem3"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "shelly_pro3em"

  [processors.override.tagpass]
    Origin = ["shelly_pro3em"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "fronius_gen24"

  [processors.override.tagpass]
    Origin = ["fronius_gen24"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "fronius_gen24_mqtt"

  [processors.override.tagpass]
    Origin = ["fronius_gen24_mqtt"]
