[[processors.override]]
  namepass = ["modbus"]

  name_override = "wp"

  [processors.override.tagpass]
    Origin = ["wp"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "smos40"

  [processors.override.tagpass]
    Origin = ["smos40"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "klimasystem2"

  [processors.override.tagpass]
    Origin = ["klimasystem2"]


[[processors.override]]
  namepass = ["modbus"]

  name_override = "klimasystem2"

  [processors.override.tagpass]
    Origin = ["klimasystem3"]
