[[processors.override]]
  namepass = ["modbus"]

  name_override = "wp"

  [processors.override.tagpass]
    Origin = ["wp"]

[[processors.override]]
  namepass = ["modbus"]

  name_override = "smos40"

  [processors.override.tagpass]
    Origin = ["smos40"]
