# =========================================================================
# OUTPUT PLUGIN (send data to InfluxDB 3)
# =========================================================================



# 1) Duplicate every metric into two labeled copies
[[processors.clone]]
	[processors.clone.tags]
		stream = "agg_1m"

[[processors.defaults]]
	[processors.defaults.tags]
		stream = "raw"


# 3) Aggregate ONLY the agg_1m stream
[[aggregators.basicstats]]
	period = "1m"
	drop_original = true
	stats  = ["mean","min","max","sum","count"]
		[aggregators.basicstats.tagpass]
    		stream = ["agg_1m"]


# 4) Route to different databases
[[outputs.influxdb_v2]]
	urls = ["http://192.168.50.164:8181"]
	token = "***REMOVED_INFLUXDB_V3_TOKEN***"
	organization = "-"
  	bucket = "home_raw"
		[outputs.influxdb_v2.tagpass]
			stream = ["raw"]

[[outputs.influxdb_v2]]
	urls = ["http://192.168.50.164:8181"]
	token = "***REMOVED_INFLUXDB_V3_TOKEN***"
	organization = "-"
  	bucket = "home"
		[outputs.influxdb_v2.tagpass]
			stream = ["agg_1m"]
