services:
  influxdb3-explorer:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb3-explorer
    user: "0:0" 
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    environment:
      SESSION_SECRET_KEY: ${key}
    volumes:
      - /srv/docker/influxdb3/explorer/config:/app-root/config
      - /srv/docker/influxdb3/explorer/ssl:/etc/nginx/ssl
      - /srv/docker/influxdb3/explorer/ca-certs:/ca-certs
      - /srv/docker/influxdb3/explorer/db:/db
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
