services:
  telegraf:
    image: telegraf:1.38.1
    container_name: telegraf3
    volumes:
      - ./config:/etc/telegraf
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
