services:
  telegraf:
    image: telegraf:1.39.1
    container_name: telegraf3
    command: >
      telegraf
      --config /etc/telegraf/telegraf.conf
      --config-directory /etc/telegraf/telegraf.d
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf.d:/etc/telegraf/telegraf.d:ro
    restart: unless-stopped
    networks:
      - homelab
networks:
  homelab:
    external: true
