# =====================================
#  Basic Telegraf Config for InfluxDB 3
# =====================================

[agent]
  interval = "10s"
  round_interval = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "1s"
  precision = "1s"
  metric_batch_size = 1000
  metric_buffer_limit = 20000

[[outputs.influxdb_v2]]
  urls = ["http://192.168.50.164:8181"]
  token = "${INFLUXDB3_TOKEN}"
  organization = "Neubauer"
  bucket_tag = "bucket"
  exclude_bucket_tag = true
