# =====================================
#  Basic Telegraf Config for InfluxDB 3
# =====================================


[agent]
	interval = "10s"
	round_interval = true
	collection_jitter = "2s"     # ~20% of interval is fine
	flush_interval = "10s"
	flush_jitter   = "1s"        # 5–20% of flush_interval; start with 1s
	precision = "1s"
	metric_batch_size   = 1000   # >= your expected points per flush (500)
	metric_buffer_limit = 20000  # ~20k points buffer (~400s of backlog at 50 pts/s)
	omit_hostname = true
	skip_processors_after_aggregators = true
