services:
   grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${grafana_admin}
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_password}  #change the password
      - GF_INSTALL_PLUGINS=
      - GF_PLUGINS_VOLKOVLABS_ECHARTS_PANEL_ENABLEJAVASCRIPT=true
    ports:
      - '3000:3000'
    volumes:
      - /srv/docker/grafana/data:/var/lib/grafana
    networks:
      - homelab
      - cloudflared-net
      
networks:
  homelab:
  cloudflared-net:
    external: true
