services:
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8085:8080"
    volumes:
      - /srv/docker/sqlite-web/data:/data
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
