services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${token}
    networks:
      - cloudflared-net
      - homelab

networks:
  homelab:
  cloudflared-net:
    external: true
