services:
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    hostname: ${NETDATA_HOSTNAME:-netdata}
    restart: unless-stopped
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /srv/docker/netdata/config:/etc/netdata
      - /srv/docker/netdata/lib:/var/lib/netdata
      - /srv/docker/netdata/cache:/var/cache/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock