services:
  aclfixer:
    container_name: maintenance_aclfixer
    image: alpine:latest
    user: root
    privileged: true
    volumes:
      - /srv/docker:/srv/docker
    command: >
      sh -c "
      echo '[ACL FIXER] Installing acl tools...' &&
      apk add --no-cache acl &&
      echo '[ACL FIXER] Applying ACLs...' &&
      setfacl -R -m u:1000:rx /srv/docker &&
      setfacl -R -d -m u:1000:rx /srv/docker &&
      echo '[ACL FIXER] Done.'
      "
    restart: "no"