services:
  telegraf:
    image: telegraf:1.36.3
    container_name: telegraf
    volumes:
     - /srv/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: unless-stopped
    networks:
      - homelab

networks:
  homelab:
    external: true
