services:
  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /srv/docker/influxdb2/lib:/var/lib/influxdb2
      - /srv/docker/influxdb2/etc:/etc/influxdb2
    networks:
      - homelab

networks:
  homelab_net:
    external: true
