version: '3.8'

services:
  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb2_lib_data:/var/lib/influxdb2
      - influxdb2_etc_data:/etc/influxdb2

volumes:
  influxdb2_lib_data:
    external: true
    name: influxdb2_lib_data
  influxdb2_etc_data:
    external: true
    name: influxdb2_etc_data
