services:
  ttyd:
    image: tsl0922/ttyd
    container_name: ttyd
    restart: unless-stopped
    command: ttyd -p 7681 bash
    ports:
      - "7681:7681"
    networks:
      - homelab

networks:
  homelab:
    external: true
